// __________________________________ DB ENGINE EVENTS

export const DB_ENGINE_EVENTS = {
    //________ TRADING DATA
    GET_MIX_HISTORICAL_DATA: 'GET_MIX_HISTORICAL_DATA',
    //________ USERS
    GET_ALL_USERS_LIST: 'GET_ALL_USERS_LIST',
    GET_USERS_BY_USER_NAMES: 'GET_USERS_BY_USER_NAMES',
    GET_USER_SHARED_USERS: 'GET_USER_SHARED_USERS',
    //________ PROCESSES
    GET_PROCESSES_BY_USER: 'GET_PROCESSES_BY_USER',
};

export type DbEngineEvents = typeof DB_ENGINE_EVENTS;


// ________________________________ BACK TESTING ENGINE EVENTS
export const BACK_TESTING_EVENTS = {
    BACK_TESTING_PROCESS_START: 'BACK_TESTING_PROCESS_START',
    BACK_TESTING_PROCESS_CANCEL: 'BACK_TESTING_PROCESS_CANCEL',
    BACK_TESTING_PROCESS_FINISH_RESPONSE: 'BACK_TESTING_PROCESS_FINISH_RESPONSE'
};

export type BackTestingEngineEvents = typeof BACK_TESTING_EVENTS;

// ________________________________ BOT ENGINE EVENTS
export const BOT_ENGINE_EVENTS = {
    BOT_ENGINE_PROCESS_START: 'BOT_ENGINE_PROCESS_START',
    BOT_ENGINE_PROCESS_STOP: 'BOT_ENGINE_PROCESS_STOP',
    REAL_TIME_CANDLES_FEED: 'REAL_TIME_CANDLES_FEED'
};

export type BotEngineEvents = typeof BOT_ENGINE_EVENTS;